//Data from the categories component located on the Homepage
export const categories = [
  {
    id: 1,
    img:require("../src/Resources/Female_Category.png"),
    title: "Femenino",
    category: "Femenino",
  },
  {
      id: 2,
      img:require("../src/Resources/Male_Category.png"),
      title: "Masculino",
      category: "Masculino",
  },
  {
      id: 3,
      img:require("../src/Resources/Childish_Category.png"),
      title: "Infantil",
      category: "Infantil",
  },
];

//Data of the benefits component located on the Homepage
export const benefits = [
  {
    id: 1,
    img:require("../src/Resources/Shield.png"),
    title: "Pago seguro",
    desc: "Protegemos los datos de tu compra",
  },
  {
    id: 2,
    img:require("../src/Resources/Calendar.png"),
    title: "Envío rapido",
    desc: "Envío directo a tu vivienda",
  },
  {
    id: 3,
    img:require("../src/Resources/CreditCard.png"),
    title: "Medios de pago",
    desc: "Recibimos varios medios de pago",
  },
  {
    id: 4,
    img:require("../src/Resources/Truck.png"),
    title: "A todo Colombia",
    desc: "Hacemos envios a todo el país",
  },
];

//Sales product data
export const Data = {
  status: "success",
  items:[
    {
      id: 1,
      title: "Pijama top con short unicolor ",
      price: 30000,
      image: require('./Resources/Female_1.png'),
      category: "Femenino",
      cantidad: 1,
      position:0,
      size: ["xs", "s", "m", "l"],
    },
    {
      id: 2,
      title: "Pijama camisa estampada con pantalón unicolor",
      price: 55000,
      image: require('./Resources/Female_2.png'),
      category: "Femenino",
      cantidad: 1,
      position:0,
      size: ["xs", "s", "m", "l"],
    },
    {
      id: 3,
      title: "Pijama durazno camisa unicolor con pantalón",
      price: 50000,
      image: require('./Resources/Female_3.png'),
      category: "Femenino",
      cantidad: 1,
      position:0,
      size: ["xs", "s", "m", "l"],
    },
    {
      id: 4,
      title: "Pijama tipo camisón unicolor",
      price: 45000,
      image: require('./Resources/Female_4.png'),
      category: "Femenino",
      cantidad: 1,
      position:0,
      size: ["xs", "s", "m", "l"],
    },
    {
      id: 5,
      title: "Pijama leñador camisa unicolor con pantalón estampado",
      price: 50000,
      image: require('./Resources/Male_1.png'),
      category: "Masculina",
      cantidad: 1,
      position:0,
      size: ["s", "m", "l", "xl"],
    },
    {
      id: 6,
      title: "Pijama semi camisa y pantalón unicolor",
      price: 55000,
      image: require('./Resources/Male_2.png'),
      category: "Masculina",
      cantidad: 1,
      position:0,
      size: ["s", "m", "l", "xl"],
    },
    {
      id: 7,
      title: "Pijama semi camisa estampada y pantalón unicolor",
      price: 45000,
      image: require('./Resources/Male_3.png'),
      category: "Masculina",
      cantidad: 1,
      position:0,
      size: ["s", "m", "l", "xl"],
    },
    {
      id: 8,
      title: "Pijama semi camisa y pantalón unicolor",
      price: 55000,
      image: require('./Resources/Male_4.png'),
      category: "Masculina",
      cantidad: 1,
      position:0,
      size: ["s", "m", "l", "xl"],
    },
    {
      id: 9,
      title: "Pijama infantil enteriza estampada",
      price: 45000,
      image: require('./Resources/Childish_1.png'),
      category: "Infantil",
      cantidad: 1,
      position:0,
      size: ["2T", "3T", "4T", "5T"],
    },
    {
      id: 10,
      title: "Pijama infantil enteriza estampada",
      price: 45000,
      image: require('./Resources/Childish_2.png'),
      category: "Infantil",
      cantidad: 1,
      position:0,
      size: ["2T", "3T", "4T", "5T"],
    },
    {
      id: 11,
      title: "Pijama infantil camisa y pantalon estampada",
      price: 50000,
      image: require('./Resources/Childish_3.png'),
      category: "Infantil",
      cantidad: 1,
      position:0,
      size: ["2T", "3T", "4T", "5T"],
    },
    {
      id: 12,
      title: "Pijama infantil enteriza estampada",
      price: 45000,
      image: require('./Resources/Childish_4.png'),
      category: "Infantil",
      cantidad: 1,
      position:0,
      size: ["2T", "3T", "4T", "5T"],
    },
  ]
}